spring:
  application:
    name: Back
  autoconfigure:
    exclude: org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME:vectordb}
    username: ${DATABASE_USERNAME:vector}
    password: ${DATABASE_PASSWORD:vector123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-dummy}
      embedding:
        options:
          model: text-embedding-3-small # ?? ?? ??
          dimensions: 384